import pytest

from data_store.data_store import DataStore, DataInvalidException


def test_data_not_1MB():
    # The provided code must be tested for 1GB instead we test it for 10KB
    with pytest .raises(DataInvalidException):
        created_files = []
        for data in range(1, 20):
            o = DataStore(key=str(data))
            o.create(value={'1': '111213165656611121316565661112131656566111213165656611121316565661112131656566111213165656611121316565661112131656566111213165656611121316565661112131656566111213165656611121316565661112131656566111213165656611121316565661112131656566111213165656611121316565661112131656566111213165656611121316565661112131656566111213165656611121316565661112131656566111213165656611121316565661112131656566111213165656611121316565661112131656566111213165656611121316565661112131656566111213165656611121316565661112131656566111213165656611121316565661112131656566111213165656611121316565661112131656566111213165656611121316565661112131656566111213165656611121316565661112131656566111213165656611121316565661112131656566111213165656611121316565661112131656566111213165656611121316565661112131656566111213165656611121316565661112131656566111213165656611121316565661112131656566111213165656611121316565661112131656566111213165656611121316565661112131656566111213165656611121316565661112131656566111213165656611121316565661112131656566111213165656611121316565661112131656566111213165656611121316565661112131656566111213165656611121316565661112131656566111213165656611121316565661112131656566111213165656611121316565661112131656566111213165656611121316565661112131656566111213165656611121316565661112131656566111213165656611121316565661112131656566111213165656611121316565661112131656566111213165656611121316565661112131656566111213165656611121316565661112131656566111213165656611121316565661112131656566111213165656611121316565661112131656566111213165656611121316565661112131656566'})
            created_files.append(o)

    for file_obj in created_files:
        file_obj.delete()
